"""make_brand_id_and_type_id_nullable

Revision ID: e18abeaecb52
Revises: ac375ab6019b
Create Date: 2025-10-23 11:59:31.153519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e18abeaecb52'
down_revision: Union[str, Sequence[str], None] = 'ac375ab6019b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
